preprocess:
    config_path: readers/configs/ria_reader_config.json
    file_path: ./raw_data/ria_test.json
    save_path: ./processed_data/output.pt
    bert_path: ./rubert_cased_L-12_H-768_A-12_pt
    lower: True
    max_src_tokens: 600
    max_tgt_tokens: 200

train:
    mode: train
    data_path: ./processed_data/output.pt
    visible_gpus: "-1"
    dec_dropout: 0.2
    model_path: ./rubert_cased_L-12_H-768_A-12_pt
    encoder: bert
    sep_optim: True
    temp_dir: ../temp
    lr_bert: 0.002
    lr_dec: 0.2
    finetune_bert: True
    save_checkpoint_steps: 5000
    batch_size: 8
    train_steps: 200000
    report_every: 400
    accum_count: 95
    use_bert_emb: True
    use_interval: True
    warmup_steps_bert: 20000
    warmup_steps_dec: 10000
    max_pos: 256
    log_file: ../logs/abs_bert_ria
    dec_layers: 6
    dec_hidden_size: 768
    dec_heads: 8
    dec_ff_size: 2048
    enc_hidden_size: 512
    enc_ff_size: 512
    enc_dropout: 0.2
    enc_layers: 6
    large: True
    load_from_extractive: ""
    share_emb: True
    ner_masking: 0
    apply_ner_masking_prob: 0.95
    ner_masked_percent: 0.85
    block_trigram: True
    report_rouge: True
    train_from: ""
    test_start_from: -1
    test_from: ""
    test_all: True
    seed: 42
    gpu_ranks: 0
    max_grad_norm: 0
    warmup_steps: 8000
    beta1: 0.9
    beta2: 0.999
    lr: 1
    optim: adam
    param_init: 0
    param_init_glorot: True
    label_smoothing: 0.1
    generator_shard_size: 32
    alpha: 0.6
    beam_size: 6
    min_length: 15
    max_length: 150
    max_tgt_len: 140
    recall_eval: False
test:
    mode: test
    batch_size: 12
    test_from: ./rubert_cased_L-12_H-768_A-12_pt/model_step_40000.pt
    visible_gpus: "-1"
    test_batch_size: 12
    data_path: ./processed_data/output.pt
    log_file: ../logs/val_abs_bert_ria
    model_path: ./rubert_cased_L-12_H-768_A-12_pt
    sep_optim: True
    use_interval: True
    max_pos: 256
    max_length: 90
    alpha: 0.95
    min_length: 8
    result_path: ../check_data
